log:
  debug: true

mysql:
  dsn: "root:root@tcp(localhost:13316)/task?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=1s&readTimeout=3s&writeTimeout=3s&multiStatements=true"

redis:
  addr: "localhost:6379"

mq:
  kafka:
    network: "tcp"
    addr: "localhost:9092"

etcd:
  addrs:
    - "127.0.0.1:2379"
  connectTimeout: "1s"
  secure: false

cache:
  local:
    capacity: 1000000
  requestTimeout: 3000000000
  valueExpiration: 600000000000

server:
  scheduler:
    grpc:
      host: "0.0.0.0"
      port: 9002
  governor:
    host: "0.0.0.0"
    port: 9003
  executor:
    grpc:
      host: "0.0.0.0"
      port: 9004

scheduler:
  batchTimeout: 3000000000
  batchSize: 100
  preemptedTimeout: 600000000000 # 10m
  scheduleInterval: 10000000000
  renewInterval: 5000000000
  maxConcurrentTasks: 1000
  tokenAcquireTimeout: 3000000000
  pollInterval: 1000000000
  reportTimeout: 10000000000

compensator:
  retry:
    maxRetryCount: 3
    prepareTimeoutWindowMs: 10000000000
    batchSize: 100
    minDuration: 1000000000

executionReportEvent:
  topic: "execution_report"
  partitions: 2

executionBatchReportEvent:
  topic: "execution_batch_report"
  partitions: 2