// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"gitee.com/flycash/distributed_task_platform/internal/grpc"
	"gitee.com/flycash/distributed_task_platform/internal/repository"
	"gitee.com/flycash/distributed_task_platform/internal/repository/dao"
	"gitee.com/flycash/distributed_task_platform/internal/service/task"
	"gitee.com/flycash/distributed_task_platform/ioc"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitSchedulerApp() *ioc.SchedulerApp {
	string2 := ioc.InitNodeID()
	v := ioc.InitDB()
	taskExecutionDAO := dao.NewGORMTaskExecutionDAO(v)
	taskDAO := dao.NewGORMTaskDAO(v)
	taskRepository := repository.NewTaskRepository(taskDAO)
	taskExecutionRepository := repository.NewTaskExecutionRepository(taskExecutionDAO, taskRepository)
	service := task.NewService(taskRepository)
	taskAcquirer := ioc.InitMySQLTaskAcquirer(taskRepository)
	mq := ioc.InitMQ()
	completeProducer := ioc.InitCompleteProducer(mq)
	executionService := task.NewExecutionService(string2, taskExecutionRepository, service, taskAcquirer, completeProducer)
	reporterServer := grpc.NewReporterServer(executionService)
	component := ioc.InitEtcdClient()
	egrpcComponent := ioc.InitSchedulerNodeGRPCServer(reporterServer, component)
	planService := task.NewPlanService(taskRepository, taskExecutionRepository)
	registry := ioc.InitRegistry(component)
	clientsV2 := ioc.InitExecutorServiceGRPCClients(registry)
	invoker := ioc.InitInvoker(clientsV2)
	runner := ioc.InitRunner(string2, service, executionService, planService, taskAcquirer, invoker, completeProducer)
	client := ioc.InitPrometheusClient()
	clusterLoadChecker := ioc.InitClusterLoadChecker(string2, client)
	scheduler := ioc.InitScheduler(string2, runner, service, executionService, taskAcquirer, clientsV2, clusterLoadChecker)
	retryCompensator := ioc.InitRetryCompensator(runner, executionService)
	rescheduleCompensator := ioc.InitRescheduleCompensator(runner, executionService)
	shardingCompensator := ioc.InitShardingCompensator(string2, service, executionService, taskAcquirer)
	batchReportEventConsumer := ioc.InitExecutionBatchReportEventConsumer(mq, string2)
	reportEventConsumer := ioc.InitExecutionReportEventConsumer(mq, string2)
	v2 := ioc.InitTasks(retryCompensator, rescheduleCompensator, shardingCompensator, batchReportEventConsumer, reportEventConsumer)
	schedulerApp := &ioc.SchedulerApp{
		GRPC:      egrpcComponent,
		Scheduler: scheduler,
		Tasks:     v2,
	}
	return schedulerApp
}

// wire.go:

var (
	BaseSet = wire.NewSet(ioc.InitDB, ioc.InitDistributedLock, ioc.InitEtcdClient, ioc.InitMQ, ioc.InitRunner, ioc.InitInvoker, ioc.InitRegistry, ioc.InitPrometheusClient)

	taskSet = wire.NewSet(dao.NewGORMTaskDAO, repository.NewTaskRepository, task.NewService)

	taskExecutionSet = wire.NewSet(dao.NewGORMTaskExecutionDAO, repository.NewTaskExecutionRepository, task.NewExecutionService)

	planSet = wire.NewSet(task.NewPlanService)

	schedulerSet = wire.NewSet(ioc.InitNodeID, ioc.InitClusterLoadChecker, ioc.InitScheduler, ioc.InitMySQLTaskAcquirer, ioc.InitExecutorServiceGRPCClients)

	compensatorSet = wire.NewSet(ioc.InitRetryCompensator, ioc.InitRescheduleCompensator, ioc.InitShardingCompensator)

	producerSet = wire.NewSet(ioc.InitCompleteProducer)

	consumerSet = wire.NewSet(ioc.InitExecutionReportEventConsumer, ioc.InitExecutionBatchReportEventConsumer)
)
