// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"gitee.com/flycash/distributed_task_platform/internal/grpc"
	"gitee.com/flycash/distributed_task_platform/internal/repository"
	"gitee.com/flycash/distributed_task_platform/internal/repository/dao"
	"gitee.com/flycash/distributed_task_platform/internal/service/task"
	"gitee.com/flycash/distributed_task_platform/ioc"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitSchedulerApp() *ioc.SchedulerApp {
	string2 := ioc.InitNodeID()
	v := ioc.InitDB()
	taskDAO := dao.NewGORMTaskDAO(v)
	taskRepository := repository.NewTaskRepository(taskDAO)
	service := task.NewService(taskRepository)
	taskExecutionDAO := dao.NewGORMTaskExecutionDAO(v)
	taskExecutionRepository := repository.NewTaskExecutionRepository(taskExecutionDAO, taskRepository)
	executionService := task.NewExecutionService(taskExecutionRepository)
	taskAcquirer := ioc.InitMySQLTaskAcquirer(service)
	clients := ioc.InitExecutorServiceGRPCClients()
	v2 := ioc.InitLocalExecuteFuncs()
	v3 := ioc.InitExecutors(clients, v2)
	mq := ioc.InitMQ()
	v4 := ioc.InitConsumers(mq, string2)
	scheduler := ioc.InitScheduler(string2, service, executionService, taskAcquirer, v3, v4, clients)
	reporterServer := grpc.NewReporterServer(scheduler)
	component := ioc.InitEtcdClient()
	egrpcComponent := ioc.InitSchedulerNodeGRPCServer(reporterServer, component)
	retryCompensator := ioc.InitRetryCompensator(service, executionService, scheduler)
	v5 := ioc.InitTasks(retryCompensator)
	schedulerApp := &ioc.SchedulerApp{
		GRPC:      egrpcComponent,
		Scheduler: scheduler,
		Tasks:     v5,
	}
	return schedulerApp
}

// wire.go:

var (
	BaseSet = wire.NewSet(ioc.InitDB, ioc.InitDistributedLock, ioc.InitEtcdClient, ioc.InitMQ, ioc.InitConsumers)

	taskSet = wire.NewSet(dao.NewGORMTaskDAO, repository.NewTaskRepository, task.NewService)

	taskExecutionSet = wire.NewSet(dao.NewGORMTaskExecutionDAO, repository.NewTaskExecutionRepository, task.NewExecutionService)

	schedulerSet   = wire.NewSet(ioc.InitNodeID, ioc.InitScheduler, ioc.InitExecutors, ioc.InitLocalExecuteFuncs, ioc.InitMySQLTaskAcquirer, ioc.InitExecutorServiceGRPCClients)
	compensatorSet = wire.NewSet(ioc.InitRetryCompensator)
)
