// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"context"
	"gitee.com/flycash/distributed_task_platform/internal/repository"
	"gitee.com/flycash/distributed_task_platform/internal/repository/dao"
	"gitee.com/flycash/distributed_task_platform/internal/service/invoker"
	"gitee.com/flycash/distributed_task_platform/internal/service/scheduler"
	"gitee.com/flycash/distributed_task_platform/internal/service/task"
	"gitee.com/flycash/distributed_task_platform/internal/test/ioc"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitSchedulerApp(execFunc map[string]invoker.LocalExecuteFunc) *SchedulerApp {
	string2 := InitNodeID()
	v := ioc.InitDBAndTables()
	taskDAO := dao.NewGORMTaskDAO(v)
	taskRepository := repository.NewTaskRepository(taskDAO)
	service := task.NewService(taskRepository)
	taskExecutionDAO := dao.NewGORMTaskExecutionDAO(v)
	taskExecutionRepository := repository.NewTaskExecutionRepository(taskExecutionDAO, taskRepository)
	taskAcquirer := InitMySQLTaskAcquirer(taskRepository)
	mq := ioc.InitMQ()
	completeProducer := InitCompleteProducer(mq)
	executionService := task.NewExecutionService(string2, taskExecutionRepository, service, taskAcquirer, completeProducer)
	localInvoker := NewExecutors(execFunc)
	invokerInvoker := initDispatcherExecutor(localInvoker)
	singleTaskRunner := InitSingleRunner(string2, service, executionService, taskAcquirer, invokerInvoker, completeProducer)
	planService := task.NewPlanService(taskRepository, taskExecutionRepository)
	planRunner := InitPlanRunner(planService, singleTaskRunner)
	runner := InitDispatchRunner(singleTaskRunner, planRunner)
	scheduler := InitScheduler(string2, runner, service, executionService, taskAcquirer)
	completeConsumer := InitCompleteConsumer(mq, planRunner, service, executionService, taskAcquirer, string2)
	retryCompensator := InitRetryCompensator(executionService, runner)
	v2 := InitTasks(retryCompensator)
	schedulerApp := &SchedulerApp{
		Scheduler:    scheduler,
		TaskSvc:      service,
		ExecutionSvc: executionService,
		Consumer:     completeConsumer,
		Tasks:        v2,
	}
	return schedulerApp
}

// wire.go:

var (
	BaseSet = wire.NewSet(ioc.InitDBAndTables, ioc.InitDistributedLock, ioc.InitEtcdClient, ioc.InitMQ, InitNodeID,
		InitConsumers,
	)

	taskSet = wire.NewSet(dao.NewGORMTaskDAO, repository.NewTaskRepository, task.NewService)

	taskExecutionSet = wire.NewSet(dao.NewGORMTaskExecutionDAO, repository.NewTaskExecutionRepository, InitCompleteProducer, task.NewExecutionService)

	planSet = wire.NewSet(task.NewPlanService)

	schedulerSet = wire.NewSet(
		NewExecutors,
		InitMySQLTaskAcquirer,
		initDispatcherExecutor,
		InitSingleRunner,
		InitPlanRunner,
		InitDispatchRunner,
		InitScheduler,
	)

	compensatorSet = wire.NewSet(
		InitRetryCompensator,
	)
)

func initDispatcherExecutor(localExecutor *invoker.LocalInvoker) invoker.Invoker {
	return invoker.NewDispatcher(nil, nil, localExecutor)
}

type Task interface {
	Start(ctx context.Context)
}

type SchedulerApp struct {
	Scheduler    *scheduler.Scheduler
	TaskSvc      task.Service
	ExecutionSvc task.ExecutionService
	Consumer     *CompleteConsumer
	Tasks        []Task
}

func (a *SchedulerApp) StartTasks(ctx context.Context) {
	for _, t := range a.Tasks {
		go func(t Task) {
			t.Start(ctx)
		}(t)
	}
}
