// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"context"
	"gitee.com/flycash/distributed_task_platform/internal/repository"
	"gitee.com/flycash/distributed_task_platform/internal/repository/dao"
	"gitee.com/flycash/distributed_task_platform/internal/service/task"
	"gitee.com/flycash/distributed_task_platform/internal/test/ioc"
	"gitee.com/flycash/distributed_task_platform/pkg/executor"
	"gitee.com/flycash/distributed_task_platform/scheduler"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitSchedulerApp(execFunc map[string]executor.LocalExecuteFunc) *SchedulerApp {
	string2 := InitNodeID()
	v := ioc.InitDBAndTables()
	taskDAO := dao.NewGORMTaskDAO(v)
	taskRepository := repository.NewTaskRepository(taskDAO)
	service := task.NewService(taskRepository)
	taskAcquirer := InitMySQLTaskAcquirer(service)
	taskExecutionDAO := dao.NewGORMTaskExecutionDAO(v)
	taskExecutionRepository := repository.NewTaskExecutionRepository(taskExecutionDAO, taskRepository)
	executionService := task.NewExecutionService(taskExecutionRepository)
	v2 := NewExecutors(execFunc)
	mq := ioc.InitMQ()
	completeProducer := InitCompleteProducer(mq)
	singleTaskRunner := InitSingleRunner(string2, service, executionService, taskAcquirer, v2, completeProducer)
	planService := task.NewPlanService(taskRepository, taskExecutionRepository)
	planRunner := InitPlanRunner(planService, singleTaskRunner)
	runner := InitDispatchRunner(string2, singleTaskRunner, planRunner)
	v3 := InitConsumers(mq, string2)
	scheduler := InitScheduler(string2, service, taskAcquirer, runner, v3)
	retryCompensator := InitRetryCompensator(service, executionService, runner)
	v4 := InitTasks(retryCompensator)
	schedulerApp := &SchedulerApp{
		Scheduler:    scheduler,
		TaskSvc:      service,
		ExecutionSvc: executionService,
		Tasks:        v4,
	}
	return schedulerApp
}

// wire.go:

var (
	BaseSet = wire.NewSet(ioc.InitDBAndTables, ioc.InitDistributedLock, ioc.InitEtcdClient, ioc.InitMQ, InitNodeID,
		InitConsumers,
	)

	taskSet = wire.NewSet(dao.NewGORMTaskDAO, repository.NewTaskRepository, task.NewService)

	taskExecutionSet = wire.NewSet(dao.NewGORMTaskExecutionDAO, repository.NewTaskExecutionRepository, task.NewExecutionService)

	planSet = wire.NewSet(task.NewPlanService)

	schedulerSet = wire.NewSet(
		NewExecutors,
		InitMySQLTaskAcquirer,
		InitCompleteProducer,
		InitSingleRunner,
		InitPlanRunner,
		InitDispatchRunner,
		InitScheduler,
	)

	compensatorSet = wire.NewSet(
		InitRetryCompensator,
	)
)

type Task interface {
	Start(ctx context.Context)
}

type SchedulerApp struct {
	Scheduler    *scheduler.Scheduler
	TaskSvc      task.Service
	ExecutionSvc task.ExecutionService
	Tasks        []Task
}

func (a *SchedulerApp) StartTasks(ctx context.Context) {
	for _, t := range a.Tasks {
		go func(t Task) {
			t.Start(ctx)
		}(t)
	}
}
